default_language_version:
  python: python3.14

repos:
  - repo: https://github.com/tsvikas/sync-with-uv
    rev: v0.4.0
    hooks:
      - id: sync-with-uv

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: biome-check
        name: biome check
        entry: bun run biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types_or: [javascript, jsx, ts, tsx, json, css]
      - id: typecheck
        name: tsc typecheck
        entry: bun run typecheck
        language: system
        types_or: [ts, tsx]
        pass_filenames: false
