# Generated by Django 3.2.14 on 2022-07-25 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_version_1_3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kegbotsite",
            name="check_for_updates",
        ),
        migrations.AddField(
            model_name="kegbotsite",
            name="email_config",
            field=models.TextField(
                default="console:",
                help_text="Backend email configuration",
                validators=[
                    django.core.validators.RegexValidator(
                        code="bad_uri",
                        message="Please enter a valid email configuration URI",
                        regex="^(console|smtp|submission|dummy|memory):",
                    )
                ],
            ),
        ),
    ]
