# Generated by Django 5.2.16 on 2026-08-03 18:59

import pykeg.core.timezones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_version_1_3_part_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kegbotsite",
            name="timezone",
            field=models.CharField(
                choices=pykeg.core.timezones.timezone_choices,
                default="UTC",
                help_text="Time zone for this system.",
                max_length=255,
            ),
        ),
    ]
