# Generated by Django 5.2.16 on 2026-08-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_timezone_choices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controller",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="flowmeter",
            options={"ordering": ("controller", "port_name")},
        ),
        migrations.AlterModelOptions(
            name="flowtoggle",
            options={"ordering": ("controller", "port_name")},
        ),
        migrations.AlterModelOptions(
            name="thermosensor",
            options={"ordering": ("raw_name",)},
        ),
    ]
