# Generated by Django 5.2.16 on 2026-08-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_hardware_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="controller",
            name="auth_token",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Bearer token for the kegboard event protocol; set when the device is paired.",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="drink",
            name="pour_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Device-assigned pour identifier (kegboard event protocol).",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
