version: '3'

services:
  kegbot:
    image: kegbot/server:stable
    restart: unless-stopped
    command: run_server
    ports:
      - "8000:8000"
    volumes:
      - kegbot-data:/kegbot-data
    tmpfs:
      - /tmp
      - /var/tmp
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: mysql://kegbot:changeme@mysql/kegbot
      KEGBOT_ENV: "debug"

  workers:
    image: kegbot/server:stable
    restart: unless-stopped
    command: run_workers
    volumes:
      - kegbot-data:/kegbot-data
    tmpfs:
      - /tmp
      - /var/tmp
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: mysql://kegbot:changeme@mysql/kegbot
      KEGBOT_ENV: "debug"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'changeme'
      MYSQL_USER: 'kegbot'
      MYSQL_PASSWORD: 'changeme'
      MYSQL_DATABASE: 'kegbot'
    tmpfs:
      - /tmp
      - /var/tmp
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always

volumes:
  mysql-data:
  kegbot-data:
