version: '3'
services:
  kegbot:
    image: kegbot/server:1.3
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - kegbot-data:/kegbot-data
    tmpfs:
      - /tmp
      - /var/tmp
    environment:
      KEGBOT_REDIS_URL: redis://redis:6379/0
      KEGBOT_DATABASE_URL: mysql://kegbot:changeme@mysql/kegbot
      KEGBOT_ENV: "debug"

  workers:
    image: kegbot-server
    restart: unless-stopped
    command: bin/kegbot run_workers
    volumes:
      - kegbot-data:/kegbot-data
    tmpfs:
      - /tmp
      - /var/tmp
    environment:
      KEGBOT_REDIS_URL: redis://redis:6379/0
      KEGBOT_DATABASE_URL: mysql://kegbot:changeme@mysql/kegbot
      KEGBOT_SETUP_ENABLED: "true"
      KEGBOT_DEBUG: "true"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'changeme'
      MYSQL_USER: 'kegbot'
      MYSQL_PASSWORD: 'changeme'
      MYSQL_DATABASE: 'kegbot'
    tmpfs:
      - /tmp
      - /var/tmp
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always

volumes:
  mysql-data:
  kegbot-data:
