# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import models_pb2 as models__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tapi.proto\x1a\x0cmodels.proto"1\n\x04Meta\x12\r\n\x05total\x18\x01 \x01(\r\x12\r\n\x05limit\x18\x02 \x01(\r\x12\x0b\n\x03pos\x18\x03 \x01(\r"r\n\x17UserRegistrationRequest\x12\x10\n\x08username\x18\x01 \x02(\t\x12\r\n\x05\x65mail\x18\x02 \x02(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\t\x12\x14\n\x0ctwitter_name\x18\x05 \x01(\t"\xef\x01\n\x12RecordDrinkRequest\x12\x10\n\x08tap_name\x18\x01 \x01(\t\x12\r\n\x05ticks\x18\x02 \x02(\r\x12\x11\n\tvolume_ml\x18\x03 \x01(\x02\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x16\n\x0bseconds_ago\x18\x05 \x01(\r:\x01\x30\x12\x13\n\x0brecord_date\x18\x06 \x01(\t\x12\x18\n\x10\x64uration_seconds\x18\x07 \x01(\r\x12\x12\n\nauth_token\x18\x08 \x01(\t\x12\x0f\n\x07spilled\x18\t \x01(\x08\x12\r\n\x05shout\x18\n \x01(\t\x12\x18\n\x10tick_time_series\x18\x0b \x01(\t"T\n\x18RecordTemperatureRequest\x12\x13\n\x0bsensor_name\x18\x01 \x02(\t\x12\x0e\n\x06temp_c\x18\x02 \x02(\x02\x12\x13\n\x0brecord_date\x18\x03 \x01(\t"\xd2\x02\n\x0cSyncResponse\x12 \n\x0b\x63ontrollers\x18\x01 \x03(\x0b\x32\x0b.Controller\x12\x16\n\x06\x64rinks\x18\x02 \x03(\x0b\x32\x06.Drink\x12\x1c\n\x06\x65vents\x18\x03 \x03(\x0b\x32\x0c.SystemEvent\x12\x19\n\x0b\x61\x63tive_kegs\x18\x04 \x03(\x0b\x32\x04.Keg\x12\x1a\n\x06meters\x18\x05 \x03(\x0b\x32\n.FlowMeter\x12\x1c\n\tsite_info\x18\x06 \x01(\x0b\x32\t.SiteInfo\x12!\n\x0csound_events\x18\x07 \x03(\x0b\x32\x0b.SoundEvent\x12\x15\n\x04taps\x18\x08 \x03(\x0b\x32\x07.KegTap\x12\x1c\n\x07toggles\x18\t \x03(\x0b\x32\x0b.FlowToggle\x12 \n\x0e\x61\x63tive_session\x18\n \x01(\x0b\x32\x08.Session\x12\x1b\n\x0c\x61\x63tive_users\x18\x0b \x03(\x0b\x32\x05.UserB\x14\n\x10org.kegbot.protoH\x02'
)


_META = DESCRIPTOR.message_types_by_name["Meta"]
_USERREGISTRATIONREQUEST = DESCRIPTOR.message_types_by_name["UserRegistrationRequest"]
_RECORDDRINKREQUEST = DESCRIPTOR.message_types_by_name["RecordDrinkRequest"]
_RECORDTEMPERATUREREQUEST = DESCRIPTOR.message_types_by_name["RecordTemperatureRequest"]
_SYNCRESPONSE = DESCRIPTOR.message_types_by_name["SyncResponse"]
Meta = _reflection.GeneratedProtocolMessageType(
    "Meta",
    (_message.Message,),
    {
        "DESCRIPTOR": _META,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:Meta)
    },
)
_sym_db.RegisterMessage(Meta)

UserRegistrationRequest = _reflection.GeneratedProtocolMessageType(
    "UserRegistrationRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERREGISTRATIONREQUEST,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:UserRegistrationRequest)
    },
)
_sym_db.RegisterMessage(UserRegistrationRequest)

RecordDrinkRequest = _reflection.GeneratedProtocolMessageType(
    "RecordDrinkRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECORDDRINKREQUEST,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:RecordDrinkRequest)
    },
)
_sym_db.RegisterMessage(RecordDrinkRequest)

RecordTemperatureRequest = _reflection.GeneratedProtocolMessageType(
    "RecordTemperatureRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECORDTEMPERATUREREQUEST,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:RecordTemperatureRequest)
    },
)
_sym_db.RegisterMessage(RecordTemperatureRequest)

SyncResponse = _reflection.GeneratedProtocolMessageType(
    "SyncResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _SYNCRESPONSE,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:SyncResponse)
    },
)
_sym_db.RegisterMessage(SyncResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\020org.kegbot.protoH\002"
    _META._serialized_start = 27
    _META._serialized_end = 76
    _USERREGISTRATIONREQUEST._serialized_start = 78
    _USERREGISTRATIONREQUEST._serialized_end = 192
    _RECORDDRINKREQUEST._serialized_start = 195
    _RECORDDRINKREQUEST._serialized_end = 434
    _RECORDTEMPERATUREREQUEST._serialized_start = 436
    _RECORDTEMPERATUREREQUEST._serialized_end = 520
    _SYNCRESPONSE._serialized_start = 523
    _SYNCRESPONSE._serialized_end = 861
# @@protoc_insertion_point(module_scope)
