# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_TESTMESSAGE = descriptor.Descriptor(
  name='TestMessage',
  full_name='TestMessage',
  filename='unittest.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='TestMessage.data', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)



class TestMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTMESSAGE


_TESTSERVICE = descriptor.ServiceDescriptor(
  name='TestService',
  full_name='TestService',
  index=0,
  options=None,
  methods=[
  descriptor.MethodDescriptor(
    name='ToLower',
    full_name='TestService.ToLower',
    index=0,
    containing_service=None,
    input_type=_TESTMESSAGE,
    output_type=_TESTMESSAGE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='ToUpper',
    full_name='TestService.ToUpper',
    index=1,
    containing_service=None,
    input_type=_TESTMESSAGE,
    output_type=_TESTMESSAGE,
    options=None,
  ),
])

class TestService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _TESTSERVICE
class TestService_Stub(TestService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _TESTSERVICE

